### ISSUE TITLE
Python error "IndexError: list index out of range"

### ISSUE THREAD

**Issue by egnerfl** [schwalle/kicktipp-betbot#8]
First of all, thanks for your awesome project! 

Since a couple of days I receive the following error, any ideas (I'm not a python dev but it seems to be a easy one)?

FYI, I'm working on a Docker image to run your script which I will publish once I'm done.

Traceback (most recent call last):
  File "/Users/egnerfl/Developer/kicktipp-betbot/./kicktippbb.py", line 267, in <module>
    main(arguments)
  File "/Users/egnerfl/Developer/kicktipp-betbot/./kicktippbb.py", line 261, in main
    place_bets(browser, communities, predictor,
  File "/Users/egnerfl/Developer/kicktipp-betbot/./kicktippbb.py", line 171, in place_bets
    matches = parse_match_rows(browser, com, matchday)
  File "/Users/egnerfl/Developer/kicktipp-betbot/./kicktippbb.py", line 111, in parse_match_rows
    ), row[4].get_text(), row[5].get_text(), row[6].get_text())
IndexError: list index out of range
 ✘ egnerfl@MacBookPro  ~/Developer/

**Comment by dmham187** [comment]
Had the same problem today. Kicktipp must have changed some HTML code. I fixed the python code so it works again. You can find it in my pull request:

https://github.com/schwalle/kicktipp-betbot/pull/9/commits/7dfbc267870036f1f838bd6750ca269ce9551b4a

**Comment by schwalle** [comment]
Thanks for the feedback!
I have the same issues, couldn't get it to work yesterday :-)
I will merge the PR from @dmham187
